dist: xenial
sudo: required

language: node_js
node_js:
  - "lts/*"

install:
  - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
  - sudo dpkg -i hugo*.deb

script:
  - if [ "$TRAVIS_BRANCH" = "production" ]; then export HUGO_BASEURL=https://edopportunity.org/; fi
  - if [ "$TRAVIS_BRANCH" = "staging" ]; then export HUGO_BASEURL=https://staging.edopportunity.org/; fi
  - hugo version # prints the Hugo version, just in case.
  - hugo # build the website

before_deploy:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

deploy:
  - skip_cleanup: true
    provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: staging.edopportunity.org
    region: us-east-1
    acl: public_read
    local_dir: public
    on:
      branch: staging
  - provider: script
    script: aws cloudfront create-invalidation --distribution-id=$CLOUDFRONT_ID_STAGING --paths="/*"
    on:
      branch: staging
  - skip_cleanup: true
    provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: edopportunity.org
    region: us-east-1
    acl: public_read
    local_dir: public
    on:
      branch: production
  - provider: script
    script: aws cloudfront create-invalidation --distribution-id=$CLOUDFRONT_ID_PRODUCTION --paths="/*"
    on:
      branch: production

env:
  global:
    - HUGO_RELEASE=0.56.3
