backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "content/uploads" # Media files will be stored in the repo under content/uploads (to make the image processing work we have to use this technique to spoof the images being page resources
public_folder: "/uploads" # The src attribute for uploaded media will begin with this

collections:
  #HOMEPAGE
  - label: News Items 
    name: newsitems
    identifier_field: headline
    folder: "data/news/"
    #filter: {field: "is_index", value: false}
    preview_path: news/
    extension: "yaml"
    create: true
    fields:
      - {label: "Headline", name: "headline", widget: string,}
      - {label: Outlet, name: outlet, widget: string,}
      - {label: Date, name: date, widget: string, hint: 'format: YYYY-MM-DD'}
      - {label: Link, name: link, widget: string}
      - {label: Excerpt, name: excerpt, widget: markdown, buttons: ['bold', 'italic']}
     